[opener]
sioyek_reuse = [
  { run = "/opt/homebrew/bin/sioyek --reuse-window %s", orphan = true, desc = "Sioyek (reuse window)", for = "macos" },
]

sioyek_new_window = [
  { run = "/opt/homebrew/bin/sioyek --new-window %s", orphan = true, desc = "Sioyek (new window)", for = "macos" },
]

zathura = [
  { run = "/opt/homebrew/bin/zathura %s", orphan = true, desc = "Zathura", for = "macos" },
]

mac_preview = [
  { run = "open -a Preview %s", orphan = true, desc = "Preview (macOS)", for = "macos" },
]

[open]
prepend_rules = [
  { mime = "application/pdf", use = ["sioyek_reuse", "sioyek_new_window", "zathura", "mac_preview"] },
  { url = "*.pdf", use = ["sioyek_reuse", "sioyek_new_window", "zathura", "mac_preview"] },
]

[plugin]

prepend_preloaders = [
    # Office Documents
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*", run = "office" },
    { mime = "application/ms-*", run = "office" },
    { mime = "application/msword", run = "office" },
    { name = "*.docx", run = "office" },
]

prepend_previewers = [
    # Office Documents
    { mime = "application/openxmlformats-officedocument.*", run = "office" },
    { mime = "application/oasis.opendocument.*", run = "office" },
    { mime = "application/ms-*", run = "office" },
    { mime = "application/msword", run = "office" },
    { name = "*.docx", run = "office" },
]
